# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='amenity name')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Hotel Amenity',
                'verbose_name_plural': 'Hotel Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='room number')),
                ('name', models.CharField(max_length=200, verbose_name='room name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('size_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='room size (sq ft)')),
                ('max_guests', models.PositiveIntegerField(default=2, verbose_name='maximum guests')),
                ('bed_count', models.PositiveIntegerField(default=1, verbose_name='number of beds')),
                ('bed_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Queen', 'Queen'), ('King', 'King'), ('Twin', 'Twin')], default='Double', max_length=50, verbose_name='bed type')),
                ('has_ac', models.BooleanField(default=True, verbose_name='has AC')),
                ('has_tv', models.BooleanField(default=True, verbose_name='has TV')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='has minibar')),
                ('has_safe', models.BooleanField(default=False, verbose_name='has safe')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='has balcony')),
                ('has_bathtub', models.BooleanField(default=False, verbose_name='has bathtub')),
                ('is_smoking_allowed', models.BooleanField(default=False, verbose_name='smoking allowed')),
                ('total_rooms', models.PositiveIntegerField(default=1, verbose_name='total rooms')),
                ('available_rooms', models.PositiveIntegerField(default=1, verbose_name='available rooms')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='base price per night')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax percentage')),
                ('cancellation_days', models.PositiveIntegerField(default=2, help_text='Days before check-in for free cancellation', verbose_name='free cancellation days')),
                ('cancellation_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='cancellation fee percentage')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Room',
                'verbose_name_plural': 'Hotel Rooms',
                'ordering': ['hotel', 'room_type', 'base_price'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/rooms/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='room type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon_class', models.CharField(blank=True, help_text='CSS class for icon (e.g., "fas fa-bed")', max_length=50, verbose_name='icon class')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='hotel name')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('star_rating', models.IntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True, verbose_name='star rating')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='average rating')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='review count')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='has WiFi')),
                ('has_pool', models.BooleanField(default=False, verbose_name='has pool')),
                ('has_gym', models.BooleanField(default=False, verbose_name='has gym')),
                ('has_spa', models.BooleanField(default=False, verbose_name='has spa')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='has restaurant')),
                ('has_parking', models.BooleanField(default=False, verbose_name='has parking')),
                ('has_airport_shuttle', models.BooleanField(default=False, verbose_name='has airport shuttle')),
                ('is_pet_friendly', models.BooleanField(default=False, verbose_name='pet friendly')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hotels/thumbnails/', verbose_name='thumbnail')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'is_active'], name='hotels_hote_city_a8c2d6_idx'), models.Index(fields=['avg_rating'], name='hotels_hote_avg_rat_9592d1_idx'), models.Index(fields=['star_rating'], name='hotels_hote_star_ra_e9d0d2_idx'), models.Index(fields=['featured'], name='hotels_hote_feature_77417f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='review title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('cleanliness', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='cleanliness')),
                ('comfort', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='comfort')),
                ('location', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='location')),
                ('facilities', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='facilities')),
                ('staff', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='staff')),
                ('value_for_money', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='value for money')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified review')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='helpful count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Review',
                'verbose_name_plural': 'Hotel Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
