# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotelroom'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_rooms', to='hotels.roomtype'),
        ),
        migrations.AddIndex(
            model_name='hotelreview',
            index=models.Index(fields=['hotel', 'rating'], name='hotels_hote_hotel_i_f67856_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelreview',
            index=models.Index(fields=['created_at'], name='hotels_hote_created_d46d14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelreview',
            unique_together={('hotel', 'user')},
        ),
        migrations.AddIndex(
            model_name='hotelroom',
            index=models.Index(fields=['hotel', 'is_available'], name='hotels_hote_hotel_i_ce8c78_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelroom',
            index=models.Index(fields=['base_price'], name='hotels_hote_base_pr_a8c813_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelroom',
            unique_together={('hotel', 'room_number')},
        ),
    ]
