# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=50, unique=True, verbose_name='bus number')),
                ('route_from', models.CharField(max_length=200, verbose_name='from')),
                ('route_to', models.CharField(max_length=200, verbose_name='to')),
                ('via_cities', models.TextField(blank=True, help_text='Comma separated list of intermediate cities', verbose_name='via cities')),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='distance (km)')),
                ('departure_time', models.TimeField(verbose_name='departure time')),
                ('arrival_time', models.TimeField(verbose_name='arrival time')),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='duration (hours)')),
                ('total_seats', models.PositiveIntegerField(default=40, verbose_name='total seats')),
                ('seats_per_row', models.PositiveIntegerField(default=4, verbose_name='seats per row')),
                ('seat_layout', models.JSONField(default=list, help_text='JSON array representing seat layout (e.g., [1,2] for 1+2 layout)', verbose_name='seat layout')),
                ('has_ac', models.BooleanField(default=False, verbose_name='has AC')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='has WiFi')),
                ('has_charging', models.BooleanField(default=False, verbose_name='has charging')),
                ('has_toilet', models.BooleanField(default=False, verbose_name='has toilet')),
                ('has_tv', models.BooleanField(default=False, verbose_name='has TV')),
                ('is_sleeper', models.BooleanField(default=False, verbose_name='sleeper bus')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='base fare')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax percentage')),
                ('cancellation_before_hours', models.PositiveIntegerField(default=4, help_text='Hours before departure for free cancellation', verbose_name='free cancellation before hours')),
                ('cancellation_charge_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='cancellation charge percentage')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['departure_time', 'bus_number'],
            },
        ),
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='operator name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='operator code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='buses/operators/', verbose_name='logo')),
                ('contact_number', models.CharField(blank=True, max_length=20, verbose_name='contact number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
            ],
            options={
                'verbose_name': 'Bus Operator',
                'verbose_name_plural': 'Bus Operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='review title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('cleanliness', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='cleanliness')),
                ('comfort', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='comfort')),
                ('punctuality', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='punctuality')),
                ('staff_behavior', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='staff behavior')),
                ('value_for_money', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='value for money')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified review')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='helpful count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bus Review',
                'verbose_name_plural': 'Bus Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(help_text='Comma separated days: MON,TUE,WED,THU,FRI,SAT,SUN', max_length=50, verbose_name='days of week')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
            ],
            options={
                'verbose_name': 'Bus Schedule',
                'verbose_name_plural': 'Bus Schedules',
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10, verbose_name='seat number')),
                ('seat_type', models.CharField(choices=[('NORMAL', 'Normal'), ('WINDOW', 'Window'), ('AISLE', 'Aisle'), ('SLEEPER', 'Sleeper')], default='NORMAL', max_length=20, verbose_name='seat type')),
                ('seat_gender', models.CharField(choices=[('ANY', 'Any'), ('MALE', 'Male Only'), ('FEMALE', 'Female Only')], default='ANY', max_length=10, verbose_name='seat gender')),
                ('row_number', models.PositiveIntegerField(verbose_name='row number')),
                ('column_number', models.PositiveIntegerField(verbose_name='column number')),
                ('fare_adjustment', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional amount for this seat (can be negative)', max_digits=10, verbose_name='fare adjustment')),
                ('is_booked', models.BooleanField(default=False, verbose_name='is booked')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='is blocked')),
                ('block_reason', models.CharField(blank=True, max_length=200, verbose_name='block reason')),
                ('is_emergency_exit', models.BooleanField(default=False, verbose_name='emergency exit')),
                ('is_near_toilet', models.BooleanField(default=False, verbose_name='near toilet')),
            ],
            options={
                'verbose_name': 'Bus Seat',
                'verbose_name_plural': 'Bus Seats',
                'ordering': ['row_number', 'column_number'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('stop_name', models.CharField(max_length=200, verbose_name='stop name')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='arrival time')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='departure time')),
                ('sequence', models.PositiveIntegerField(verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Bus Stop',
                'verbose_name_plural': 'Bus Stops',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='bus type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Bus Type',
                'verbose_name_plural': 'Bus Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('travel_date', models.DateField(verbose_name='travel date')),
                ('seats_booked', models.JSONField(default=list, help_text='List of seat numbers booked', verbose_name='seats booked')),
                ('total_passengers', models.PositiveIntegerField(verbose_name='total passengers')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount')),
                ('passenger_name', models.CharField(max_length=200, verbose_name='passenger name')),
                ('passenger_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='passenger age')),
                ('passenger_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='passenger gender')),
                ('passenger_phone', models.CharField(max_length=20, verbose_name='passenger phone')),
                ('passenger_email', models.EmailField(blank=True, max_length=254, verbose_name='passenger email')),
                ('boarding_point', models.CharField(max_length=200, verbose_name='boarding point')),
                ('dropping_point', models.CharField(max_length=200, verbose_name='dropping point')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20, verbose_name='status')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('cancellation_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cancellation charge')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='buses.bus')),
            ],
            options={
                'verbose_name': 'Bus Booking',
                'verbose_name_plural': 'Bus Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
