# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='buses.busoperator'),
        ),
        migrations.AddField(
            model_name='busreview',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='buses.busbooking'),
        ),
        migrations.AddField(
            model_name='busreview',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busseat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='buses.bus'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='buses.bustype'),
        ),
        migrations.AddIndex(
            model_name='busbooking',
            index=models.Index(fields=['user', 'status'], name='buses_busbo_user_id_d273e1_idx'),
        ),
        migrations.AddIndex(
            model_name='busbooking',
            index=models.Index(fields=['bus', 'travel_date'], name='buses_busbo_bus_id_d65f35_idx'),
        ),
        migrations.AddIndex(
            model_name='busbooking',
            index=models.Index(fields=['created_at'], name='buses_busbo_created_4bd3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='busreview',
            index=models.Index(fields=['bus', 'rating'], name='buses_busre_bus_id_a6a529_idx'),
        ),
        migrations.AddIndex(
            model_name='busreview',
            index=models.Index(fields=['created_at'], name='buses_busre_created_4bafcd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='busreview',
            unique_together={('bus', 'user', 'booking')},
        ),
        migrations.AddIndex(
            model_name='busseat',
            index=models.Index(fields=['bus', 'is_booked', 'is_blocked'], name='buses_busse_bus_id_42fbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='busseat',
            index=models.Index(fields=['seat_type'], name='buses_busse_seat_ty_316d51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='busseat',
            unique_together={('bus', 'seat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('bus', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['route_from', 'route_to', 'departure_time'], name='buses_bus_route_f_6be33d_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['operator', 'bus_type'], name='buses_bus_operato_2e1c57_idx'),
        ),
        migrations.AddIndex(
            model_name='bus',
            index=models.Index(fields=['status'], name='buses_bus_status_dbbe52_idx'),
        ),
    ]
