# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='brand name')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cars/brands/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Car Category',
                'verbose_name_plural': 'Car Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='feature name')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Car Feature',
                'verbose_name_plural': 'Car Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='registration number')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('year', models.PositiveIntegerField(verbose_name='manufacturing year')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='AUTOMATIC', max_length=20, verbose_name='transmission')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('CNG', 'CNG')], default='PETROL', max_length=20, verbose_name='fuel type')),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='engine capacity (cc)')),
                ('mileage_kmpl', models.DecimalField(blank=True, decimal_places=1, help_text='Kilometers per liter', max_digits=4, null=True, verbose_name='mileage (kmpl)')),
                ('seating_capacity', models.PositiveIntegerField(default=5, verbose_name='seating capacity')),
                ('baggage_capacity', models.PositiveIntegerField(default=2, help_text='Number of suitcases', verbose_name='baggage capacity')),
                ('has_ac', models.BooleanField(default=True, verbose_name='has AC')),
                ('has_bluetooth', models.BooleanField(default=True, verbose_name='has Bluetooth')),
                ('has_gps', models.BooleanField(default=False, verbose_name='has GPS')),
                ('has_usb', models.BooleanField(default=True, verbose_name='has USB ports')),
                ('has_child_seat', models.BooleanField(default=False, verbose_name='has child seat')),
                ('is_airbag_available', models.BooleanField(default=True, verbose_name='airbags available')),
                ('is_pet_allowed', models.BooleanField(default=False, verbose_name='pet allowed')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='daily rate')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='7-day rate (optional discount)', max_digits=10, null=True, verbose_name='weekly rate')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='30-day rate (optional discount)', max_digits=10, null=True, verbose_name='monthly rate')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='security deposit')),
                ('km_limit_per_day', models.PositiveIntegerField(default=250, help_text='Free kilometers per day', verbose_name='km limit per day')),
                ('extra_km_charge', models.DecimalField(decimal_places=2, default=10.0, help_text='Charge per extra kilometer', max_digits=6, verbose_name='extra km charge')),
                ('pickup_location', models.CharField(max_length=255, verbose_name='pickup location')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cars/thumbnails/', verbose_name='thumbnail')),
                ('insurance_number', models.CharField(blank=True, max_length=100, verbose_name='insurance number')),
                ('insurance_valid_until', models.DateField(blank=True, null=True, verbose_name='insurance valid until')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='last service date')),
                ('next_service_due', models.DateField(blank=True, null=True, verbose_name='next service due')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.carbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.carcategory')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='rating')),
                ('title', models.CharField(max_length=200, verbose_name='review title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('cleanliness', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='cleanliness')),
                ('comfort', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='comfort')),
                ('performance', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='performance')),
                ('fuel_efficiency', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='fuel efficiency')),
                ('value_for_money', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='value for money')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified review')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='helpful count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car Review',
                'verbose_name_plural': 'Car Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
