# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['city', 'status', 'is_active'], name='cars_car_city_fe840e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category', 'daily_rate'], name='cars_car_categor_11084a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand', 'model'], name='cars_car_brand_i_7dc02b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['featured'], name='cars_car_feature_9c207c_idx'),
        ),
        migrations.AddIndex(
            model_name='carreview',
            index=models.Index(fields=['car', 'rating'], name='cars_carrev_car_id_c0123c_idx'),
        ),
        migrations.AddIndex(
            model_name='carreview',
            index=models.Index(fields=['created_at'], name='cars_carrev_created_9d1750_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carreview',
            unique_together={('car', 'user')},
        ),
    ]
