# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TICKET', 'Ticket'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt'), ('CONFIRMATION', 'Confirmation'), ('CANCELLATION', 'Cancellation'), ('ID_PROOF', 'ID Proof'), ('OTHER', 'Other')], max_length=20, verbose_name='document type')),
                ('name', models.CharField(max_length=200, verbose_name='document name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='bookings/documents/%Y/%m/%d/', verbose_name='file')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Document',
                'verbose_name_plural': 'Booking Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('WAITLISTED', 'Waitlisted'), ('RAC', 'RAC (Reservation Against Cancellation)')], max_length=20, verbose_name='old status')),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('WAITLISTED', 'Waitlisted'), ('RAC', 'RAC (Reservation Against Cancellation)')], max_length=20, verbose_name='new status')),
                ('old_payment_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded')], max_length=20, verbose_name='old payment status')),
                ('new_payment_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded')], max_length=20, verbose_name='new payment status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CONFIRMATION', 'Booking Confirmation'), ('CANCELLATION', 'Booking Cancellation'), ('REMINDER', 'Reminder'), ('PAYMENT', 'Payment Notification'), ('STATUS_UPDATE', 'Status Update'), ('PROMOTIONAL', 'Promotional')], max_length=20, verbose_name='notification type')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], max_length=20, verbose_name='channel')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is sent')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Notification',
                'verbose_name_plural': 'Booking Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_cancellation_policy', models.CharField(choices=[('FLEXIBLE', 'Flexible - Free cancellation up to 24 hours'), ('MODERATE', 'Moderate - Free cancellation up to 48 hours'), ('STRICT', 'Strict - Free cancellation up to 7 days'), ('NON_REFUNDABLE', 'Non-refundable')], default='MODERATE', max_length=20, verbose_name='default cancellation policy')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=365, help_text='Maximum days in advance a booking can be made', verbose_name='maximum advance booking days')),
                ('min_advance_booking_hours', models.PositiveIntegerField(default=2, help_text='Minimum hours before service for booking', verbose_name='minimum advance booking hours')),
                ('payment_timeout_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before pending booking is cancelled', verbose_name='payment timeout minutes')),
                ('auto_cancel_unpaid', models.BooleanField(default=True, help_text='Automatically cancel bookings if payment not completed', verbose_name='auto cancel unpaid bookings')),
                ('send_booking_confirmation', models.BooleanField(default=True, verbose_name='send booking confirmation')),
                ('send_reminder_before', models.PositiveIntegerField(default=24, help_text='Hours before service to send reminder', verbose_name='send reminder before hours')),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='service fee percentage')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tax percentage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(blank=True, max_length=20, unique=True, verbose_name='booking reference')),
                ('service_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('CAR', 'Car Rental'), ('BUS', 'Bus Ticket'), ('TRAIN', 'Train Ticket')], max_length=20, verbose_name='service type')),
                ('service_id', models.UUIDField(verbose_name='service ID')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='booking date')),
                ('check_in_date', models.DateField(blank=True, null=True, verbose_name='check-in date')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='check-out date')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='travel date')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('adults', models.PositiveIntegerField(default=1, verbose_name='adults')),
                ('children', models.PositiveIntegerField(default=0, verbose_name='children')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='base amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='tax amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('WAITLISTED', 'Waitlisted'), ('RAC', 'RAC (Reservation Against Cancellation)')], default='PENDING', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded')], default='PENDING', max_length=20, verbose_name='payment status')),
                ('contact_name', models.CharField(max_length=200, verbose_name='contact name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='contact phone')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('cancellation_date', models.DateTimeField(blank=True, null=True, verbose_name='cancellation date')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='refund amount')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Service-specific booking details (seats, room numbers, etc.)', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date'],
            },
        ),
    ]
