# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingdocument',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingnotification',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_type', 'service_id'], name='bookings_bo_service_4249c6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='bookings_bo_booking_f34616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in_date'], name='bookings_bo_check_i_5b803e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['travel_date'], name='bookings_bo_travel__83d735_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingdocument',
            index=models.Index(fields=['booking', 'document_type'], name='bookings_bo_booking_7d88c1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingdocument',
            index=models.Index(fields=['is_verified'], name='bookings_bo_is_veri_1940ae_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_96ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['user', 'is_read'], name='bookings_bo_user_id_8e89b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['booking', 'notification_type'], name='bookings_bo_booking_af6435_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['is_sent'], name='bookings_bo_is_sent_68401e_idx'),
        ),
    ]
