# Generated by Django 6.0.1 on 2026-01-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainreview',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='trains.trainbooking'),
        ),
        migrations.AddField(
            model_name='trainreview',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trains.train'),
        ),
        migrations.AddField(
            model_name='trainreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainstop',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trains.train'),
        ),
        migrations.AddField(
            model_name='trainbooking',
            name='from_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_bookings', to='trains.trainstop'),
        ),
        migrations.AddField(
            model_name='trainbooking',
            name='to_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_bookings', to='trains.trainstop'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['coach', 'is_booked', 'is_blocked'], name='trains_seat_coach_i_c4ba06_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['berth_type'], name='trains_seat_berth_t_c9a750_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('coach', 'seat_number')},
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['train', 'coach_type', 'status'], name='trains_coac_train_i_f00d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['available_seats'], name='trains_coac_availab_eacc0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('train', 'coach_number')},
        ),
        migrations.AddIndex(
            model_name='trainreview',
            index=models.Index(fields=['train', 'rating'], name='trains_trai_train_i_0e8d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainreview',
            index=models.Index(fields=['created_at'], name='trains_trai_created_b70985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainreview',
            unique_together={('train', 'user', 'booking')},
        ),
        migrations.AlterUniqueTogether(
            name='trainstop',
            unique_together={('train', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='trainbooking',
            index=models.Index(fields=['user', 'status'], name='trains_trai_user_id_c39382_idx'),
        ),
        migrations.AddIndex(
            model_name='trainbooking',
            index=models.Index(fields=['train', 'travel_date'], name='trains_trai_train_i_f823f3_idx'),
        ),
        migrations.AddIndex(
            model_name='trainbooking',
            index=models.Index(fields=['pnr_number'], name='trains_trai_pnr_num_b83925_idx'),
        ),
        migrations.AddIndex(
            model_name='trainbooking',
            index=models.Index(fields=['booked_at'], name='trains_trai_booked__3bf490_idx'),
        ),
    ]
